apiVersion: v1
kind: Service
metadata:
  labels:
    team: apps
  name: react-demo-app
  namespace: apps
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: react-demo-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    strategy.spinnaker.io/use-source-capacity: "true"
  labels:
    app: react-demo-app
    team: apps
  name: react-demo-app
  namespace: apps
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: react-demo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: react-demo-app
        team: apps
    spec:
      containers:
      - env:
        - name: URL_PREFIX
          value: fas-demo.app.az-eastus-1
        image: eu.gcr.io/cognitedata/apps/react-demo-app
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /fas-demo-prod/configMap.json
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        name: react-demo-app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /fas-demo-prod/configMap.json
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  annotations:
    external-dns.ambassador-service: ambassador-apps.apps
  labels:
    app: react-demo-app
    team: apps
  name: react-demo-app
  namespace: apps
spec:
  acmeProvider:
    authority: none
  ambassador_id: ambassador-apps
  hostname: fas-demo.app.az-eastus-1.cogniteapp.com
  tlsSecret:
    name: apps-certificate-cogniteapp-com-secret
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    app: react-demo-app
    team: apps
  name: react-demo-app
  namespace: apps
spec:
  add_response_headers:
    Strict-Transport-Security: max-age=31536000
  ambassador_id: ambassador-apps
  host: fas-demo.app.az-eastus-1.cogniteapp.com
  prefix: /
  rewrite: ""
  service: react-demo-app
  timeout_ms: 30000
