name: Cleanup on PR close

on:
  pull_request:
    types:
      - closed

jobs:
  delete-preview-docs:
    name: Delete preview docs
    concurrency: deploy-preview-documentation
    runs-on: ubuntu-latest
    steps: 
      - name: Initialize variables
        run: |
          echo "PR_NUMBER=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Create empty directory
        run: |
          mkdir empty_dir
        
      - name: Delete preview docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.REVEAL_DOCS_PREVIEW_DEPLOY_KEY }}
          external_repository: cognitedata/reveal-docs-preview
          publish_branch: master
          publish_dir: empty_dir/
          destination_dir: ${{ env.PR_NUMBER }}
          keep_files: false 
