name: Sync added and deleted keys to locize
on:
  push:
    branches:
      - pramodcog/UX-1220

jobs:
  locize-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: yarn --network-timeout 1000000 --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}

      - name: 'Save added keys to locize'
        working-directory: react-components
        run: yarn save-missing
        env:
          LOCIZE_API_KEY: ${{ secrets.LOCIZE_API_KEY }}

      - name: 'Remove deleted keys from locize'
        working-directory: react-components
        run: yarn remove-deleted
        env:
          LOCIZE_API_KEY: ${{ secrets.LOCIZE_API_KEY }}
