name: Nightly Publish Package to NPM
on:
  schedule:
    - cron: '0 5 * * 1-5'

permissions:
  id-token: write  # Required for OIDC trusted publishing
  contents: read

jobs:
  deploy-to-npm:
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install NPM dependencies
        working-directory: viewer
        run: yarn install --immutable

      - name: Get nightly version
        working-directory: viewer
        run: echo "NIGHTLY_VERSION=$(jq -r .version ./package.json | echo $(grep -oP '([0-9]+.[0-9]+.[0-9]+)') | echo $(< /dev/stdin)-dev.$(date +'%Y%m%d'))" >> $GITHUB_ENV

      - name: Set nightly version
        working-directory: viewer
        run: npm version ${{ env.NIGHTLY_VERSION }}

      - name: Build production version
        working-directory: viewer
        run: yarn run build:prod

      - name: Publish to NPM
        working-directory: viewer
        run: npm publish --tag nightly
