name: Publish Viewer Package to NPM
on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC trusted publishing
  contents: read

jobs:
  deploy-to-npm:
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Install NPM dependencies
        working-directory: viewer
        run: |
          sudo apt update
          sudo apt install libxi-dev libgl-dev libglx-dev
          yarn install --immutable

      - name: Build production version
        working-directory: viewer
        run: yarn run build:prod

      - name: Publish to NPM
        working-directory: viewer
        run: npm publish
