name: Move Platypus CLI Documentation to public docs
on:
  push:
    branches:
      - master
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: andstor/copycat-action@v3
        with:
          src_path: ./apps/platypus-cdf-cli
          file_filter: *.md
          dst_path: /
          dst_owner: cognitedata
          dst_branch: docs
          dst_repo_name: https://github.com/cognitedata/platypus
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
