name: Publish package

on:
  push:
    branches: ['main']

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node ğŸ
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          cache: yarn

      - name: Install ğŸ”§
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}

      - name: Lint ğŸ”§
        run: yarn lint

      - name: Test ğŸ”§
        run: yarn test

      - name: Build ğŸ”§
        run: yarn build

      - name: Publish npm package ğŸš€
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
